const mongoose = require('mongoose');

// One question per calendar day (IST). Generated by Gemini the first time any
// student requests it that day, then served from this cache for everyone.
const dailyChallengeSchema = new mongoose.Schema(
  {
    date: { type: String, required: true, unique: true }, // YYYY-MM-DD in Asia/Kolkata
    category: { type: String, required: true }, // DSA | Aptitude | CS Fundamentals | HR | Verbal
    question: { type: String, required: true },
    options: { type: [String], required: true },
    correctIndex: { type: Number, required: true },
    explanation: { type: String, default: '' },
    source: { type: String, default: 'gemini' }, // gemini | fallback
    attemptCount: { type: Number, default: 0 },
    correctCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

module.exports =
  mongoose.models.DailyChallenge || mongoose.model('DailyChallenge', dailyChallengeSchema);
